default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres
  password: postgres
  port: 5432

development:
  <<: *default
  database: books_manager_api_development

test:
  <<: *default
  database: books_manager_api_test
